export const typography = {
  fontFamily: {
    regular: 'Lexend_400Regular',
    medium: 'Lexend_500Medium',
    semiBold: 'Lexend_600SemiBold',
    bold: 'Lexend_700Bold',
  },
  fontSize: {
    displayLarge: 48,
    displayMedium: 40,
    displaySmall: 32,
    headlineLarge: 28,
    headlineMedium: 24,
    headlineSmall: 20,
    titleLarge: 20,
    titleMedium: 16,
    titleSmall: 14,
    bodyLarge: 16,
    bodyMedium: 14,
    bodySmall: 12,
    labelLarge: 14,
    labelMedium: 12,
    labelSmall: 10,
  },
  lineHeight: {
    displayLarge: 56,
    displayMedium: 48,
    displaySmall: 40,
    headlineLarge: 36,
    headlineMedium: 32,
    headlineSmall: 28,
    titleLarge: 28,
    titleMedium: 24,
    titleSmall: 20,
    bodyLarge: 24,
    bodyMedium: 20,
    bodySmall: 16,
    labelLarge: 20,
    labelMedium: 16,
    labelSmall: 14,
  },
} as const;
