run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - contextcheck
    - errname
    - errorlint
    - exportloopref
    - forcetypeassert
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - misspell
    - nakedret
    - prealloc
    - predeclared
    - revive
    - unconvert
    - unparam
    - whitespace

linters-settings:
  errcheck:
    check-blank: true
  govet:
    enable-all: true
    disable:
      - fieldalignment
  goconst:
    min-len: 3
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/contigo/backend
  gosec:
    excludes:
      - G104

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - gocritic
    - path: configs/
      linters:
        - gocritic

output:
  sort-results: true
