import 'package:flutter/material.dart';
import 'app_colors.dart';
import 'app_typography.dart';
import 'extensions.dart';
import 'theme_components.dart';

ThemeData createDarkTheme() {
  return buildContigoTheme(
    brightness: Brightness.dark,
    colorScheme: ColorScheme.dark(
      primary: AppColors.dark.primary,
      onPrimary: AppColors.dark.onPrimary,
      primaryContainer: AppColors.dark.primaryContainer,
      onPrimaryContainer: AppColors.dark.onPrimaryContainer,
      primaryFixed: AppColors.dark.primaryFixed,
      primaryFixedDim: AppColors.dark.primaryFixedDim,
      onPrimaryFixed: AppColors.dark.onPrimaryFixed,
      onPrimaryFixedVariant: AppColors.dark.onPrimaryFixedVariant,
      secondary: AppColors.dark.secondary,
      onSecondary: AppColors.dark.onSecondary,
      secondaryContainer: AppColors.dark.secondaryContainer,
      onSecondaryContainer: AppColors.dark.onSecondaryContainer,
      secondaryFixed: AppColors.dark.secondaryFixed,
      secondaryFixedDim: AppColors.dark.secondaryFixedDim,
      onSecondaryFixed: AppColors.dark.onSecondaryFixed,
      onSecondaryFixedVariant: AppColors.dark.onSecondaryFixedVariant,
      tertiary: AppColors.dark.tertiary,
      onTertiary: AppColors.dark.onTertiary,
      tertiaryContainer: AppColors.dark.tertiaryContainer,
      onTertiaryContainer: AppColors.dark.onTertiaryContainer,
      tertiaryFixed: AppColors.dark.tertiaryFixed,
      tertiaryFixedDim: AppColors.dark.tertiaryFixedDim,
      onTertiaryFixed: AppColors.dark.onTertiaryFixed,
      onTertiaryFixedVariant: AppColors.dark.onTertiaryFixedVariant,
      error: AppColors.dark.error,
      onError: AppColors.dark.onError,
      errorContainer: AppColors.dark.errorContainer,
      onErrorContainer: AppColors.dark.onErrorContainer,
      surface: AppColors.dark.surface,
      onSurface: AppColors.dark.onSurface,
      surfaceDim: AppColors.dark.surfaceDim,
      surfaceBright: AppColors.dark.surfaceBright,
      surfaceContainerLowest: AppColors.dark.surfaceContainerLowest,
      surfaceContainerLow: AppColors.dark.surfaceContainerLow,
      surfaceContainer: AppColors.dark.surfaceContainer,
      surfaceContainerHigh: AppColors.dark.surfaceContainerHigh,
      surfaceContainerHighest: AppColors.dark.surfaceContainerHighest,
      onSurfaceVariant: AppColors.dark.onSurfaceVariant,
      surfaceTint: AppColors.dark.surfaceTint,
      inverseSurface: AppColors.dark.inverseSurface,
      onInverseSurface: AppColors.dark.inverseOnSurface,
      inversePrimary: AppColors.dark.inversePrimary,
      outline: AppColors.dark.outline,
      outlineVariant: AppColors.dark.outlineVariant,
      scrim: AppColors.dark.scrim,
    ),
    textTheme: TextTheme(
      displayLarge: AppTypography.displayLarge,
      displayMedium: AppTypography.displayMedium,
      displaySmall: AppTypography.displaySmall,
      headlineLarge: AppTypography.headlineLarge,
      headlineMedium: AppTypography.headlineMedium,
      headlineSmall: AppTypography.headlineSmall,
      titleLarge: AppTypography.titleLarge,
      titleMedium: AppTypography.titleMedium,
      titleSmall: AppTypography.titleSmall,
      bodyLarge: AppTypography.bodyLarge,
      bodyMedium: AppTypography.bodyMedium,
      bodySmall: AppTypography.bodySmall,
      labelLarge: AppTypography.labelLarge,
      labelMedium: AppTypography.labelMedium,
      labelSmall: AppTypography.labelSmall,
    ),
    extensions: [
      ContigoColors.dark(),
      ContigoTypography.regular(),
      ContigoSpacing.regular(),
      ContigoRadius.regular(),
      ContigoGradients.dark(),
      ContigoShadows.regular(),
      ContigoMotion.regular(),
    ],
  );
}
