import 'package:flutter/material.dart';
import 'app_colors.dart';
import 'app_typography.dart';
import 'extensions.dart';
import 'theme_components.dart';

ThemeData createLightTheme() {
  return buildContigoTheme(
    brightness: Brightness.light,
    colorScheme: ColorScheme.light(
      primary: AppColors.light.primary,
      onPrimary: AppColors.light.onPrimary,
      primaryContainer: AppColors.light.primaryContainer,
      onPrimaryContainer: AppColors.light.onPrimaryContainer,
      primaryFixed: AppColors.light.primaryFixed,
      primaryFixedDim: AppColors.light.primaryFixedDim,
      onPrimaryFixed: AppColors.light.onPrimaryFixed,
      onPrimaryFixedVariant: AppColors.light.onPrimaryFixedVariant,
      secondary: AppColors.light.secondary,
      onSecondary: AppColors.light.onSecondary,
      secondaryContainer: AppColors.light.secondaryContainer,
      onSecondaryContainer: AppColors.light.onSecondaryContainer,
      secondaryFixed: AppColors.light.secondaryFixed,
      secondaryFixedDim: AppColors.light.secondaryFixedDim,
      onSecondaryFixed: AppColors.light.onSecondaryFixed,
      onSecondaryFixedVariant: AppColors.light.onSecondaryFixedVariant,
      tertiary: AppColors.light.tertiary,
      onTertiary: AppColors.light.onTertiary,
      tertiaryContainer: AppColors.light.tertiaryContainer,
      onTertiaryContainer: AppColors.light.onTertiaryContainer,
      tertiaryFixed: AppColors.light.tertiaryFixed,
      tertiaryFixedDim: AppColors.light.tertiaryFixedDim,
      onTertiaryFixed: AppColors.light.onTertiaryFixed,
      onTertiaryFixedVariant: AppColors.light.onTertiaryFixedVariant,
      error: AppColors.light.error,
      onError: AppColors.light.onError,
      errorContainer: AppColors.light.errorContainer,
      onErrorContainer: AppColors.light.onErrorContainer,
      surface: AppColors.light.surface,
      onSurface: AppColors.light.onSurface,
      surfaceDim: AppColors.light.surfaceDim,
      surfaceBright: AppColors.light.surfaceBright,
      surfaceContainerLowest: AppColors.light.surfaceContainerLowest,
      surfaceContainerLow: AppColors.light.surfaceContainerLow,
      surfaceContainer: AppColors.light.surfaceContainer,
      surfaceContainerHigh: AppColors.light.surfaceContainerHigh,
      surfaceContainerHighest: AppColors.light.surfaceContainerHighest,
      onSurfaceVariant: AppColors.light.onSurfaceVariant,
      surfaceTint: AppColors.light.surfaceTint,
      inverseSurface: AppColors.light.inverseSurface,
      onInverseSurface: AppColors.light.inverseOnSurface,
      inversePrimary: AppColors.light.inversePrimary,
      outline: AppColors.light.outline,
      outlineVariant: AppColors.light.outlineVariant,
      scrim: AppColors.light.scrim,
    ),
    textTheme: TextTheme(
      displayLarge: AppTypography.displayLarge,
      displayMedium: AppTypography.displayMedium,
      displaySmall: AppTypography.displaySmall,
      headlineLarge: AppTypography.headlineLarge,
      headlineMedium: AppTypography.headlineMedium,
      headlineSmall: AppTypography.headlineSmall,
      titleLarge: AppTypography.titleLarge,
      titleMedium: AppTypography.titleMedium,
      titleSmall: AppTypography.titleSmall,
      bodyLarge: AppTypography.bodyLarge,
      bodyMedium: AppTypography.bodyMedium,
      bodySmall: AppTypography.bodySmall,
      labelLarge: AppTypography.labelLarge,
      labelMedium: AppTypography.labelMedium,
      labelSmall: AppTypography.labelSmall,
    ),
    extensions: [
      ContigoColors.light(),
      ContigoTypography.regular(),
      ContigoSpacing.regular(),
      ContigoRadius.regular(),
      ContigoGradients.light(),
      ContigoShadows.regular(),
      ContigoMotion.regular(),
    ],
  );
}
